### ISSUE TITLE
Having trouple converting the messages. 

### ISSUE THREAD

**Issue by Kjartank** [matteocontrini/sms-wp-to-android#18]
Hi. I'm trying to get my 6k messages over on my android, but the cmd shows some errors. Am I doing it wrong? What I get is this one. 
Thanks in advance! :)

> Traceback (most recent call last):
  File "C:\Users\Kjartans\Downloads\Convert\sms-wp-to-android-master\convert.py", line 13, in <module>
    e = ET.parse(file_path).getroot()
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: reference to invalid character number: line 867, column 1064

**Comment by Kjartank** [comment]
I read through some of the other issues and I believe that it worked now. 
Thanks a lot! You are a god amongst mere men! And if I only could do the same with MMS...
