### ISSUE TITLE
Invalid character number

### ISSUE THREAD

**Issue by PrismaticPolygon** [matteocontrini/sms-wp-to-android#20]
Stack `trace:

```
Traceback (most recent call last):
  File "convert.py", line 13, in <module>
    e = ET.parse(file_path).getroot()
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: reference to invalid character number: line 421, column 44417`
```

Any ideas? I've checked the character specified, it's a nondescript 'm'. Same error in the same place each time. Thanks.

**Comment by matteocontrini** [comment]
Can you check that character again? There must be something wrong with it

**Comment by PrismaticPolygon** [comment]
I've sorted it now, thanks - the character that was the problem wasn't the one identified. Very useful script!
