### ISSUE TITLE
Error with vmsg

### ISSUE THREAD

**Issue by mbissoli** [matteocontrini/sms-wp-to-android#22]
I've used the script to convert the sms extracted from a WP10 phone with the "transfer my data" app. However, the output file is not a msg, but a vmsg. When I use the script, I get back this error:

Traceback (most recent call last):
  File "convert.py", line 13, in <module>
    e = ET.parse(file_path).getroot()
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1176, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 653, in parse
    parser.feed(data)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1623, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1487, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: syntax error: line 1, column 0

Can you help me?

Thank you!

**Comment by matteocontrini** [comment]
https://github.com/matteocontrini/sms-wp-to-android/issues/15#issuecomment-234647401
