### ISSUE TITLE
No output seen

### ISSUE THREAD

**Issue by ianniow** [matteocontrini/sms-wp-to-android#23]
I am not sure where the output file should appear but I get this in the terminal window

> 
C:\Temp\sms-wp>convert.py
Traceback (most recent call last):
  File "C:\Temp\sms-wp\convert.py", line 13, in <module>
    e = ET.parse(file_path).getroot()
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: reference to invalid character number: line 1,
 column 17416

> 
Not sure what to do next using windows 7 and python2.76

**Comment by matteocontrini** [comment]
See #20 #7 #11 #12

**Comment by ianniow** [comment]
Thanks not familiar with github did not see the closed issues. Also was not aware that the errors were refering to my .msg file. 
Thanks for replying quickly

**Comment by matteocontrini** [comment]
Did you manage to solve the issue?

**Comment by ianniow** [comment]
Yes I did thank you it was the " &#x11;" that was causing the error in the .msg file. 
For a newbie like me it was not obvious to look there as the messages were referring to other files.
