### ISSUE TITLE
Error in converting

### ISSUE THREAD

**Issue by rmsmgaspar** [matteocontrini/sms-wp-to-android#31]
Hi,
Using your script have the following error:

# python.exe convert.py
Traceback (most recent call last):
  File "convert.py", line 22, in <module>
    e = ET.parse(file_path).getroot()
  File "c:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "c:\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "c:\Python27\lib\xml\etree\ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "c:\Python27\lib\xml\etree\ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: reference to invalid character number: line 23, column 3831

**Comment by matteocontrini** [comment]
See previous closed issues, please
