### ISSUE TITLE
I get errors while script works…

### ISSUE THREAD

**Issue by pipicici** [matteocontrini/sms-wp-to-android#38]
Traceback (most recent call last):
  File "C:\Users\convert.py", line 21, in <module>
    e = ET.parse(file_path).getroot()
  File "D:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "D:\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "D:\Python27\lib\xml\etree\ElementTree.py", line 1653, in feed
    self._raiseerror(v)
  File "D:\Python27\lib\xml\etree\ElementTree.py", line 1517, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: reference to invalid character number: line 1, column 16551

**Comment by matteocontrini** [comment]
See #7 #11 #12 #20 
It's usually an issue with the `&#x11;` character. You can replace it in the source file using a text editor.

**Comment by pipicici** [comment]
Sorry, matteocontrini.
Just only 1 open issue was viewed as default when click "Issue" tab. It's difficult to see for newbie.
Thank you again! Great job!
