### ISSUE TITLE
&#x11; still generating issues

### ISSUE THREAD

**Issue by matteocontrini** [matteocontrini/sms-wp-to-android#58]
It should have been fixed with e3bec298442dcba30a677a898d282760c883687f, but it appears it's not.

See #56, #57.

```
λ python convert.py
Traceback (most recent call last):
  File "convert.py", line 27, in <module>
    e = ET.parse(file_path).getroot()
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 656, in parse
    parser.feed(data)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "C:\Python27\lib\xml\etree\ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: reference to invalid character number: line 1707, column 8641
```

**Comment by matteocontrini** [comment]
The workaround in the meanwhile is to open the source file in a text editor and replace every occurence of `&#x11;` with an empty string.

**Comment by sontungduog** [comment]
ok thank you! I got a same error.
