### ISSUE TITLE
Am running to the following error when i open .msg file

### ISSUE THREAD

**Issue by njorogedk** [matteocontrini/sms-wp-to-android#59]
Traceback (most recent call last):
  File "convert.py", line 27, in <module>
    e = ET.parse(file_path).getroot()
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1182, in parse
    tree.parse(source, parser)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 656, in parse
    parser.feed(data)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1659, in feed
    self._raiseerror(v)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1523, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: reference to invalid character number: line 108, column 15916

**Comment by matteocontrini** [comment]
Hi, try opening the .msg file in a text editor and replace all the occurences of the `&#x11;` sequenze of character into an empty space, then retry the conversion.

Let me know if you're able to get through it.
